services:
  db:
    image: postgres:16
    container_name: shortener_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - shortener_pg_data:/var/lib/postgresql/data

  shortener:
    build: .
    container_name: shortener_app
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default
      - edge

volumes:
  shortener_pg_data:

networks:
  edge:
    external: true
